.gitignore
src/ytdl_sub/entries/base_entry.py
src/ytdl_sub/entries/soundcloud.py
src/ytdl_sub/entries/variables/soundcloud_variables.py
tests/unit/entries/test_soundcloud_entries.py

The property will get the total tracks of the sound cloud album via the album_tracks method. If the sound cloud album is a single it will return 1.

Added total_tracks to SoundCloudAlbum

---

src/ytdl_sub/downloaders/downloader.py
src/ytdl_sub/downloaders/soundcloud_downloader.py
src/ytdl_sub/downloaders/youtube_downloader.py
src/ytdl_sub/entries/base_entry.py
src/ytdl_sub/entries/soundcloud.py
src/ytdl_sub/entries/youtube.py

Rewrite all download strategies to use info.json files in the working directory. This makes the pattern the same across all download strategies:
1. Download entry dicts not seen before (always includes 'parent' entries like channel, playlist, album, etc)
2. Differentiate which entry dict is what type of media
3. Return the media coerced as the 'base' media (ie return SoundcloudTracks and SoundcloudAlbumTracks as a list of SoundcloudTracks)

Use info.json files for all download strategies

---

README.md
config.yaml
docker/root/defaults/config.yaml
examples/kodi_music_videos_config.yaml
examples/kodi_music_videos_subscriptions.yaml
examples/kodi_tv_shows_config.yaml
examples/kodi_tv_shows_subscriptions.yaml
src/ytdl_sub/config/preset_options.py
src/ytdl_sub/entries/variables/entry_variables.py
src/ytdl_sub/entries/variables/soundcloud_variables.py
src/ytdl_sub/plugins/nfo_tags.py
tests/unit/entries/conftest.py
tests/unit/entries/test_soundcloud_entries.py

Instead of a prefix, for better doc sorting.
https://github.com/jmbannon/ytdl-sub/issues/33

Make `sanitized` a variable suffix

---

Makefile
docs/config.rst
src/ytdl_sub/config/config_file.py
src/ytdl_sub/config/preset.py
src/ytdl_sub/main.py
src/ytdl_sub/subscriptions/subscription.py
src/ytdl_sub/validators/validators.py

https://github.com/jmbannon/ytdl-sub/issues/43
And improved error message when an OverridesFormatter used a non-override variable

Umask support, fix overrides formatter variable error message

---

examples/soundcloud_discography_config.yaml
src/ytdl_sub/cli/main_args_parser.py
src/ytdl_sub/downloaders/downloader.py
src/ytdl_sub/downloaders/youtube/merge_playlist.py
src/ytdl_sub/downloaders/youtube/split_video.py
src/ytdl_sub/downloaders/youtube_downloader.py
src/ytdl_sub/entries/entry.py
src/ytdl_sub/main.py
src/ytdl_sub/plugins/music_tags.py
src/ytdl_sub/plugins/nfo_tags.py
src/ytdl_sub/plugins/output_directory_nfo_tags.py
src/ytdl_sub/plugins/plugin.py
src/ytdl_sub/subscriptions/subscription.py
src/ytdl_sub/utils/file_handler.py
src/ytdl_sub/utils/logger.py
src/ytdl_sub/ytdl_additions/enhanced_download_archive.py
tests/e2e/expected_download.py
tests/e2e/soundcloud/test_soundcloud_discography.py
tests/e2e/youtube/test_channel_as_kodi_tv_show.py
tests/e2e/youtube/test_merge_playlist.py
tests/e2e/youtube/test_playlist_as_kodi_music_videos.py
tests/e2e/youtube/test_split_video.py

https://github.com/jmbannon/ytdl-sub/issues/78
Required massive refactoring. ytdl-sub can now report what gets downloaded and where, as well as show metadata that would otherwise be hard to manually verify.
Follow-up issues:
https://github.com/jmbannon/ytdl-sub/issues/90
https://github.com/jmbannon/ytdl-sub/issues/89
https://github.com/jmbannon/ytdl-sub/issues/88
https://github.com/jmbannon/ytdl-sub/issues/87

Add `--dry-run` argument

---

src/ytdl_sub/downloaders/youtube/split_video.py
src/ytdl_sub/subscriptions/subscription.py
src/ytdl_sub/utils/file_handler.py
src/ytdl_sub/ytdl_additions/enhanced_download_archive.py

Made sense before the enhanced download archive, but now, copying is a waste of space

[BACKEND] Move files from working to output directory instead of copying

---

src/ytdl_sub/validators/url_validator.py
tests/unit/validators/test_url_validator.py

This fixes issue #106
I thought Id at least give it a shot, after your comment in issue #106.
I decided to remove the bad_url match for "www.youtube.com/channel" as it could technically be a good url with these changes, as long as there is a channel out there named "channel".
Id be very happy to change anything youd like to change.

[BUGFIX] Fix youtube url validator for channels without 'c', 'channel' or 'user'

---

src/ytdl_sub/validators/validators.py
tests/unit/validators/test_regex_validator.py

```
some_value:
- "single_element"
```
can now be defined as:
```
some_value: "single_element"
```
Behind the scenes, will cast it to a list with one element

[BACKEND] Allow list validators to support length-1 lists without defining a yaml list

---

src/ytdl_sub/entries/variables/entry_variables.py
tests/unit/entries/conftest.py
tests/unit/entries/test_entry.py
tests/unit/entries/test_soundcloud_entries.py

https://github.com/jmbannon/ytdl-sub/issues/189
Adds reverse date variables to make more recently uploaded content have a lower ordering, i.e.
`Season {upload_year_truncated_reversed} Episode {upload_month_reversed}{upload_day_reversed_padded}`
2022-01-01 -> Season 78 Episode 1231
2022-01-02 -> Season 78 Episode 1230
...
2022-12-31 -> Season 78 Episode 101
2023-01-01 -> Season 77 Episode 1231

[FEATURE] Add reversed date variables

---

src/ytdl_sub/config/preset.py
tests/unit/config/test_preset.py

```
presets:
- preset_1
- preset_2
```
preset_2 now overwrites preset_1

[BUGFIX] Fix preset ordering

---

examples/tv_show_config.yaml
src/ytdl_sub/cli/download_args_parser.py
src/ytdl_sub/config/config_file.py
src/ytdl_sub/config/config_validator.py
src/ytdl_sub/config/preset.py
src/ytdl_sub/config/preset_options.py
src/ytdl_sub/downloaders/generic/collection_validator.py
src/ytdl_sub/downloaders/soundcloud/albums_and_singles.py
src/ytdl_sub/downloaders/youtube/channel.py
src/ytdl_sub/downloaders/youtube/playlist.py
src/ytdl_sub/downloaders/youtube/video.py
src/ytdl_sub/plugins/audio_extract.py
src/ytdl_sub/plugins/file_convert.py
src/ytdl_sub/plugins/music_tags.py
src/ytdl_sub/plugins/nfo_tags.py
src/ytdl_sub/plugins/regex.py
src/ytdl_sub/plugins/split_by_chapters.py
src/ytdl_sub/plugins/video_tags.py
src/ytdl_sub/prebuilt_presets/__init__.py
src/ytdl_sub/prebuilt_presets/music_videos/jellyfin-music-videos.yaml
src/ytdl_sub/prebuilt_presets/music_videos/kodi_music_videos.yaml
src/ytdl_sub/prebuilt_presets/tv_show/tv_show_collection.yaml
src/ytdl_sub/subscriptions/base_subscription.py
src/ytdl_sub/validators/nfo_validators.py
src/ytdl_sub/validators/strict_dict_validator.py
src/ytdl_sub/validators/validators.py
tests/unit/cli/test_download_args_parser.py
tests/unit/config/test_config_file.py
tests/unit/config/test_preset.py

https://github.com/jmbannon/ytdl-sub/issues/299
If a preset was not used in a config file, absolutely no validation was performed on it. This can give users the idea that it's valid when it's not. This change will now perform 'lightweight' validation for each preset in the config.
For existing ytdl-sub users, you may now get a validation error with valid presets in this scenario:
- specify a source with no download strategy
Just add the respective download strategy and you should be good to go.

[BACKEND] More strict validation for config files

---

examples/music_videos_subscriptions.yaml

Found a typo in the example command arguments

[DOCS] Fix typo in music_videos_subscriptions.yaml

---

src/ytdl_sub/utils/file_handler.py

Extends the fix in #400 to handle all potential OSError errno values and attempt a copy/delete in all cases. For example, a combination cross-device move and a permissions change would throw errno 1 instead of errno 18, which wasn't caught here. Instead of messing with individual errno numbers, just always attempt a copy/delete and let those throw their own exceptions if they don't work either.

Always perform copy/delete on OSError

---

docs/install.rst

The provided `docker-compose.yml` config is not valid YAML, due to a missing space in the last line.

Fix yaml syntax for initial docker-compose setup

---

README.md

There was a typo in the shell command in the One-time Download section.

[DOCS] Fix typo in One-time Download

---

src/ytdl_sub/plugins/chapters.py
src/ytdl_sub/plugins/split_by_chapters.py
src/ytdl_sub/utils/chapters.py

Use yt-dlp's chapter metadata instead of relying on ffprobe

[BUGFIX] Fix Windows split by chapters not reading chapter titles correctly

---

src/ytdl_sub/cli/main.py

Didn't realize why the configuration option wasn't working at first, then I realized the warning printed the wrong option.

Fix --update-with-info-json message

---

src/ytdl_sub/cli/main.py

Today, the transaction logs are being output like below: 
```
Files modified:
----------------------------------------
/mnt/storage/media/Youtube/Abom79
.ytdl-sub-abom79-download-archive.jsonNo files changed for BlacktailStudioNo files changed for DashnerDesignRestorationNo files changed for FixingFurniture
```
Adding a line break before each subscriptions will output:
```
Files modified:
----------------------------------------
/mnt/storage/media/Youtube/Abom79
.ytdl-sub-abom79-download-archive.json
No files changed for BlacktailStudio
No files changed for DashnerDesignRestoration
No files changed for FixingFurniture
```

Add line break to transaction logs

---

docs/config.rst
src/ytdl_sub/config/preset_class_mappings.py
src/ytdl_sub/plugins/format.py
src/ytdl_sub/prebuilt_presets/helpers/common.yaml
src/ytdl_sub/prebuilt_presets/tv_show/tv_show.yaml
src/ytdl_sub/subscriptions/subscription_ytdl_options.py
tests/e2e/plugins/test_audio_extract.py
tests/e2e/plugins/test_chapters.py
tests/e2e/plugins/test_date_range.py
tests/e2e/plugins/test_music_tags.py
tests/e2e/plugins/test_nfo_tags.py
tests/e2e/plugins/test_regex.py
tests/e2e/plugins/test_split_by_chapters.py
tests/e2e/plugins/test_subtitles.py
tests/e2e/soundcloud/test_soundcloud_discography.py
tests/e2e/youtube/test_channel.py
tests/e2e/youtube/test_playlist.py
tests/e2e/youtube/test_video.py
tests/unit/config/test_config_file.py

Makes setting yt-dlp's `format` field easier by giving it its own documented plugin.
Old:
```
my_format_preset:
ytdl_options:
format: "best"
```
New:
```
my_format_preset:
format: "best"
```
The old method will still work, so do not worry about updating configs ASAP. However, the option is available to save a few lines   :wink:

[FEATURE] `format` plugin to set yt-dlp format easier

---

src/ytdl_sub/plugins/date_range.py
src/ytdl_sub/utils/datetime.py

Convert yt-dlp date formats (i.e. `today-2months`) into a date string with format `YYYYMMDD`

[BUGFIX] Fix date_range plugin as a match-filter

---

src/ytdl_sub/prebuilt_presets/helpers/players.yaml

https://github.com/jmbannon/ytdl-sub/issues/729

[BACKEND] Add `!is_live` match-filter by default to TV show presets

---

docs/config.rst
src/ytdl_sub/config/plugin.py
src/ytdl_sub/downloaders/info_json/info_json_downloader.py
src/ytdl_sub/downloaders/source_plugin.py
src/ytdl_sub/downloaders/url/downloader.py
src/ytdl_sub/plugins/match_filters.py
src/ytdl_sub/subscriptions/subscription_download.py
src/ytdl_sub/subscriptions/subscription_ytdl_options.py
tests/e2e/plugins/test_match_filters.py

Closes Issue: https://github.com/jmbannon/ytdl-sub/issues/729
Add a new field to the match_filter plugin: `download_match_filters`. This set of filters will be applied at the download stage (as opposed to `filters` which get applied at the metadata stage). By default, always set `"!is_live & !is_upcoming & !post_live"` as a download filter. This prevents ytdl-sub from hanging when trying to grab live and upcoming videos.
Docs on match-filters: https://ytdl-sub.readthedocs.io/en/latest/config.html#match-filters

[BACKEND] Always filter out live, post_live, and upcoming videos on download

---

docs/config.rst
docs/index.rst
src/ytdl_sub/config/config_validator.py
src/ytdl_sub/subscriptions/subscription.py
tests/unit/config/test_subscription.py

`Subscription Values` are how you can achieve one-liner subscriptions. This feature allows you to set it within the config. In the near future, ytdl-sub will strive to make subscription files simpler by hiding most of the "under-the-hood" logic within the config file.

[FEATURE] Ability to add subscription value via config

---

docs/config.rst
docs/deprecation_notices.rst
src/ytdl_sub/subscriptions/subscription.py
src/ytdl_sub/subscriptions/subscription_validators.py
src/ytdl_sub/validators/validators.py
tests/unit/config/test_subscription.py

https://github.com/jmbannon/ytdl-sub/issues/743
Subscriptions support using presets as keys, and using keys to set override variables as values.
For example:
```
tv_show:
only_recent:
[News]:
"Breaking News": "https://www.youtube.com/@SomeBreakingNews"
[Tech]:
"Two Minute Papers": "https://www.youtube.com/@TwoMinutePapers"
```
Will create two subscriptions named "Breaking News" and "Two Minute Papers", equivalent to:
```
"Breaking News":
preset:
- "tv_show"
- "only_recent"
overrides:
subscription_indent_1: "News"
subscription_name: "Breaking News"
subscription_value: "https://www.youtube.com/@SomeBreakingNews"
"Two Minute Papers":
preset:
- "tv_show"
overrides:
subscription_indent_1: "Tech"
subscription_name: "Two Minute Papers"     subscription_value: …
```

[FEATURE] Subscription nesting

---

src/ytdl_sub/cli/main.py
src/ytdl_sub/cli/main_args_parser.py
src/ytdl_sub/config/config_file.py
src/ytdl_sub/config/config_validator.py
tests/e2e/plugins/internal/test_view.py
tests/e2e/youtube/test_playlist.py
tests/unit/main/test_main.py

The only required field in a config was `working_directory`. This is now optional (defaults to `.ytdl-sub-working-directory`) making it so a config is no longer required. This sets the stage to onboard noob users who will solely use prebuilt presets

[FEATURE] No longer require a config.yaml

---

examples/tv_show_subscriptions.yaml
src/ytdl_sub/config/config_validator.py
src/ytdl_sub/config/preset_options.py
src/ytdl_sub/subscriptions/subscription_validators.py
src/ytdl_sub/subscriptions/utils.py
tests/unit/config/test_subscription.py

Extends the subscription.yaml syntax at the cost of introducing a breaking change.
```
TV Show | = Kids | = TV-Y | Only Recent:
"Jake Trains": "https://..."
```
```
TV Show | = Kids | = TV-Y | Only Recent:
"Jake Trains":
- "https://url.1..."  # Assigns to subscription_value and subscription_value_1
- "https://url.2..."  # Assigns to subscription_value_2
```
```
TV Show | = Kids | = TV-Y | Only Recent:
"~Jake Trains":  # the ~ means "all keys underneath get assigned as override variables"
url: "https://url.1..."  # Assigns to url
url2: "https://url.2..."  # Assigns to url2
```
In the TV show subscriptions example (https://github.com/jmbannon/ytdl-sub/blob/master/examples/tv_show_subscriptions.yaml), it had
```
TV Show Full Archive:
= Kids | TV-Y:
"Jake Trains": …
```

[FEATURE] Extend subscription syntax

---

src/ytdl_sub/plugins/nfo_tags.py
src/ytdl_sub/plugins/output_directory_nfo_tags.py
tests/e2e/plugins/test_nfo_tags.py

In addition, do not write empty tags

[FEATURE] Create output_directory_nfo_tags first instead of last

---

ytdl-sub.spec

ytdl-sub executables did not include the prebuilt music presets. This change fixes that and prevents the issue from happening again for all future prebuilt presets

[BUGFIX] Include music prebuilt presets (and all future ones) in executables

---

README.md
docker/root/defaults/subscriptions.yaml
examples/advanced/tv_show_config.yaml
examples/tv_show_subscriptions.yaml
src/ytdl_sub/config/preset_options.py
src/ytdl_sub/prebuilt_presets/helpers/common.yaml
src/ytdl_sub/subscriptions/subscription_download.py
src/ytdl_sub/validators/string_formatter_validators.py
src/ytdl_sub/ytdl_additions/enhanced_download_archive.py
tests/e2e/youtube/test_channel.py
tests/resources/transaction_log_summaries/youtube/test_channel_full_keep_max_files.txt

Adds a new mechanism to limit subscriptions' number of videos to an explicit number (only supported date ranges prior to this).
Example usage:
```
output_options:
keep_max_files: 10
```
will only keep 10 videos at max.
In addition:
- `keep_max_files` is bundled into the `Only Recent` preset and can be used via setting the `only_recent_max_files` override variable (see examples or README for usage).
- Changed the `date_range` variable name to `only_recent_date_range` for more clarity.  Usage of `date_range` will continue to work.

[FEATURE] Add `output_options.keep_max_files` to limit number of downloads per subscription

---

src/ytdl_sub/plugins/file_convert.py

Whenever the input file and converted file have the same name, the file convert plugin will delete the output file.  Fixed by moving the deletion of the input file before renaming the temporary file to the desired output name.

[BUGFIX]: File convert plugin deletes output file

---

src/ytdl_sub/entries/base_entry.py
tests/e2e/soundcloud/test_soundcloud_discography.py
tests/resources/expected_downloads_summaries/bandcamp/test_artist_url.json
tests/unit/conftest.py
tests/unit/entries/conftest.py

For less popular sites, ytdl-sub's custom download archive was not working. This was because we weren't using the right extraction key (though it still worked for YouTube, Bandcamp, Soundcloud, and others). This bugfix should now exactly match yt-dlp's and never be a problem again.
Huge thanks to @Svagtlys for root-causing this :handshake:

[BUGFIX] Use proper extractor key for download archive

---

src/ytdl_sub/script/types/function.py
src/ytdl_sub/utils/scriptable.py
tests/unit/script/functions/test_array_functions.py

Python would think a recursive error occurred, but in reality, the stack got too large due to poor optimization when executing array reduce functions. Thanks Melissa for the bug report!

[BUGFIX] Fix recursion limit when applying large reduce functions

---

src/ytdl_sub/downloaders/url/downloader.py
src/ytdl_sub/downloaders/url/validators.py
src/ytdl_sub/entries/entry_parent.py
src/ytdl_sub/prebuilt_presets/music/music.yaml
tests/unit/config/test_config_file.py

Partial fix to https://github.com/jmbannon/ytdl-sub/issues/853
Makes computing sibling metadata optional, defaulted to False. This prevents excessive memory usage when scraping large channels

[BACKEND] Make sibling metadata optional to compute

---

src/ytdl_sub/subscriptions/subscription_validators.py
tests/unit/config/test_subscription.py

Fixes the bug (https://github.com/jmbannon/ytdl-sub/issues/844) where subscription names would drop periods from them, i.e. `Mr. Beast` would have the name ` Beast`. 
**POTENTIAL BREAKING CHANGE**
If you have a subscription with a period in its name prior to this fix, this change will make it so your download archive is not found since it uses the subscription name in the download archive file path. To fix, simply change the download archive JSON's name to have the actual subscription name, and not the dropped-period one.

[BUGFIX] Fix periods not working in subscription names

---

docs/source/config_reference/scripting/override_variables.rst
src/ytdl_sub/entries/variables/override_variables.py
src/ytdl_sub/subscriptions/subscription_validators.py
tests/unit/config/test_subscription.py

To be used later for advanced presets. For subscriptions in the form of (+ as prefix)
```
+ Subscription Name:
Music Videos:
- "https://url1.com/..."
Concerts:
- "https://url2.com/..."
```
Stores all the contents under the subscription name into the override variable
``subscription_map`` as a Map value. The above example is stored as:
```
{
"Music Videos": [
"https://url1.com/..."
],
"Concerts: [
"https://url2.com/..."
]
}
```
Advanced scripting is needed to dissect this Map variable into a usable preset

[FEATURE] `subscription_map` value

---

src/ytdl_sub/downloaders/info_json/info_json_downloader.py
src/ytdl_sub/entries/base_entry.py
src/ytdl_sub/entries/entry.py
src/ytdl_sub/plugins/subtitles.py
src/ytdl_sub/subscriptions/subscription_ytdl_options.py
tests/e2e/youtube/test_playlist.py

Should hopefuly fix both:
- https://github.com/jmbannon/ytdl-sub/issues/843
- https://github.com/jmbannon/ytdl-sub/issues/867
Various sites have unique IDs with characters that get sanitized (i.e. `/`, `:`). `ytdl-sub` was not using sanitized UIDs when looking for files, and would throw an error saying download was missing. This should resolve that issue.

[BUGFIX] Properly handle UIDs that have misbehaving chars that get sanitized

---

src/ytdl_sub/subscriptions/subscription_download.py
src/ytdl_sub/subscriptions/subscription_ytdl_options.py

Implements: https://github.com/jmbannon/ytdl-sub/issues/829
Optimization to not scrape more than what you will keep

[BACKEND] Set `max_downloads` to `keep_max_files` if present

---

src/ytdl_sub/config/overrides.py
src/ytdl_sub/downloaders/url/downloader.py
src/ytdl_sub/entries/base_entry.py
src/ytdl_sub/entries/entry.py
src/ytdl_sub/subscriptions/subscription_ytdl_options.py
src/ytdl_sub/utils/scriptable.py
tools/docgen/plugins.py

Reduce memory usage significantly when pulling large channels all at once by
- Not loading entry script until it is being processed
- Deleting the entry memory once fully processed
- Disable yt-dlp from keeping entry info in memory since ytdl-sub reads it from file

[BACKEND] Optimize memory usage

---

src/ytdl_sub/cli/entrypoint.py
src/ytdl_sub/cli/parsers/main.py
src/ytdl_sub/main.py
src/ytdl_sub/utils/logger.py
tests/unit/cli/test_entrypoint.py
tests/unit/main/test_main.py
tests/unit/utils/test_logger.py

Implements https://github.com/jmbannon/ytdl-sub/issues/880
and maybe fixes https://github.com/jmbannon/ytdl-sub/issues/827
Can now do `ytdl-sub sub --match SubA SubB` or `ytdl-sub sub --match SubA --match SubB`, which will only run subscriptions that contain `SubA` or `SubB` in their names

[FEATURE] `--match` flag to only run subset of subscriptions

---

src/ytdl_sub/cli/entrypoint.py
src/ytdl_sub/cli/parsers/dl.py
src/ytdl_sub/cli/parsers/main.py
src/ytdl_sub/subscriptions/subscription.py
tests/e2e/youtube/test_playlist.py
tests/unit/cli/test_entrypoint.py

With both `--match` and `--dl-override`, it is now possible to more easily experiment with subscriptions without needing to create a separate file.
For example, suppose you are changing some values in your subscription "Rick A" and want to test them out. You can now run:
```
ytdl-sub sub --dry-run --match Rick --dl-override '--ytdl-options.max_downloads 3'
```
This will
1. Dry-run
2. Only run for the subscription "Rick A"
3. Apply setting max_downloads to 3

[FEATURE] Add `--dl-override` to pass dl arg overrides to all subscriptions

---

src/ytdl_sub/downloaders/url/downloader.py
src/ytdl_sub/downloaders/ytdlp.py
src/ytdl_sub/entries/entry_parent.py

Makes it possible to fix https://github.com/jmbannon/ytdl-sub/issues/756
In the case that uploader_url does not equal the input url, keep trying to fetch uploader_url to get all possible metadata that yt-dlp does not provide in a single API call

[BACKEND] Try to fetch source metadata from uploader_url

---

src/ytdl_sub/subscriptions/subscription_ytdl_options.py

Fixes https://github.com/jmbannon/ytdl-sub/issues/892
Does not set max_downloads if keep_max_files = 0

[BUGFIX] keep_max_files=0 downloading 2

---

src/ytdl_sub/plugins/split_by_chapters.py

Usage of `chapter_title_sanitized` would sometimes result in an error. This should hopefully fix it

[BUGFIX] Fix usage of `chapter_title_sanitized`

---

src/ytdl_sub/entries/script/variable_definitions.py

Fixes https://github.com/jmbannon/ytdl-sub/issues/912
If a required variable (like uid) is missing, ytdl-sub will error. This bugfix prevents sites that do not provide an upload date from erroring.

[BUGFIX] Use epoch_date if upload_date is missing

---

src/ytdl_sub/prebuilt_presets/music/singles.yaml

As title, to make it easier to override

[FEATURE] Add dedicated `track_date` and `track_original_date` variables

---

README.md
docs/source/config_reference/subscriptions_yaml.rst
docs/source/prebuilt_presets/tv_shows.rst
examples/tv_show_subscriptions.yaml
src/ytdl_sub/prebuilt_presets/music/other_websites.yaml
src/ytdl_sub/prebuilt_presets/tv_show/__init__.py
src/ytdl_sub/prebuilt_presets/tv_show/tv_show.yaml
src/ytdl_sub/prebuilt_presets/tv_show/tv_show_collection.yaml
tests/resources/expected_downloads_summaries/youtube/test_channel_full.json
tests/unit/config/test_subscription.py

Simplifies TV Show Collection presets, drastically. Old version:
```
rick_a_tv_show_collection:
preset:
- "jellyfin_tv_show_collection"
- "season_by_collection__episode_by_year_month_day_reversed"
- "collection_season_1"
- "collection_season_2"
overrides:
tv_show_name: "Rick A"
collection_season_1_url: "https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw"
collection_season_1_name: "All Videos"
collection_season_2_url: "https://www.youtube.com/playlist?list=PLlaN88a7y2_plecYoJxvRFTLHVbIVAOoc"
collection_season_2_name: "Official Music Videos"
```
New version:
```
Jellyfin TV Show Collection:
"~Rick A":
s01_name: "All Videos"
s01_url: "https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw"
s02_name: "Official Music Videos"
s02_url: …
```

[FEATURE] Simplify TV Show Collection Preset

---

docs/source/config_reference/scripting/scripting_functions.rst
src/ytdl_sub/script/functions/regex_functions.py
tests/unit/script/functions/test_regex_functions.py

This implements %regex_sub built-in function to enhance string-processing capabilities, allowing users to perform substitutes like:
* removing non-ascii characters
* replacing subsequent whitespace characters with a single whitespace
Also added a couple of tests to cover the added functionality.

Add %regex_sub built-in script function

---

docs/source/config_reference/scripting/scripting_functions.rst
src/ytdl_sub/config/config_validator.py
src/ytdl_sub/entries/script/custom_functions.py
tests/unit/config/test_config_file.py
tests/unit/config/test_preset.py

Fixes path with tildes in them, i.e. `~/videos/youtube`

[BUGFIX] Fix usage of ~ in paths

---

src/ytdl_sub/script/functions/conditional_functions.py
src/ytdl_sub/script/script.py
src/ytdl_sub/script/types/function.py
src/ytdl_sub/script/types/variable_dependency.py
src/ytdl_sub/script/utils/type_checking.py
src/ytdl_sub/utils/script.py
tests/unit/script/functions/test_conditional_functions.py
tests/unit/script/types/test_lambda_function.py
tools/docgen/scripting_functions.py

Will only run branches of `if` statements if the condition evaluates to that branch

[BUGFIX] Do not run all branches of `if` functions in scripts

---

docker/root/defaults/config.yaml

Still learning how to use this project but I noticed the link in the default config seems to be a 404, I added what I believe to be the correct one in its place

Fixing 404 link to presets

---

docs/source/guides/install/linux.rst

There was an issue where it didn't have a  ./ in front of the ytdl-sub -h command

[DOCS] Fix command syntax on the linux install page

---

src/ytdl_sub/entries/entry.py

youtube info.json sometimes say ext: mkv but download is not mkv. then ffmpeg fail because source file not exist. change ext property to find correct ext if info.json gives wrong ext.

[BUGFIX] Find ext when info.json wrong

---

src/ytdl_sub/utils/file_handler.py

This prevents MemoryError when running on systems with less memory than the file being processed.
Fixes https://github.com/jmbannon/ytdl-sub/issues/1051.

get_file_md5_hash: read small blocks instead of the entire file

---

docs/source/config_reference/scripting/scripting_functions.rst
src/ytdl_sub/script/functions/string_functions.py
src/ytdl_sub/subscriptions/subscription_validators.py
tests/unit/config/test_subscription.py
tests/unit/script/functions/test_string_functions.py

Adds the function `%contains_any`, and list support in a tilda override subscription. The end-goal of these features are to more easily add a title exclude list, like so:
```
__preset__:
filter_exclude:
- "{%contains_any( %lower(title), exclude_title_strings )}"
...
Jellyfin TV Show by Date:
~History Documentaries:
url: "https://..."
exclude_title_strings:
- "trailer"
- "preview"
```
A proper prebuilt preset or built-in functionality will follow this change.

[BACKEND] `%contains_any` function, list + dict support for tilda overrides mode

---

docs/source/prebuilt_presets/helpers.rst
src/ytdl_sub/config/overrides.py
src/ytdl_sub/config/preset_options.py
src/ytdl_sub/prebuilt_presets/helpers/download_deletion_options.yaml
src/ytdl_sub/subscriptions/subscription_ytdl_options.py
tests/e2e/bandcamp/test_bandcamp.py

Adds the ability to use override variables in the [ytdl_options](https://ytdl-sub.readthedocs.io/en/latest/config_reference/plugins.html#ytdl-options) section of the config.

[FEATURE] Override variable support in ytdl_options

---

docs/source/guides/getting_started/automating_downloads.rst

Fixes cron paths in documentation.
Spotted these when configuring. Then noticed #1073  was already open.
Resolves #1073

Fix documentation for cron path

---

docs/source/config_reference/scripting/scripting_functions.rst
docs/source/prebuilt_presets/helpers.rst
src/ytdl_sub/prebuilt_presets/helpers/filtering.yaml
src/ytdl_sub/script/functions/string_functions.py
tests/integration/prebuilt_presets/test_filter_keywords.py
tests/unit/script/functions/test_string_functions.py

Keyword evaluation behavior toggleable

[FEATURE] Toggleable keyword evaluation behavior

---

docs/source/guides/getting_started/automating_downloads.rst

This could be a gap in knowledge on how to run CRON jobs out of a Docker container but it seems like it does come up often. Small change to add a note to tell users to restart their Docker container for changes in the guide to take effect.
Related:
- #1155 
- https://discord.com/channels/994270357957648404/1238315252525957160/1238315252525957160

[DOCS] Add note to restart Docker container

---

.github/workflows/release.yaml

v3 now deprecated: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

[BACKEND] Use upload-artifact@v4

---

src/ytdl_sub/__init__.py
src/ytdl_sub/cli/output_summary.py

Hope this is not too much of a bother. I just had a bit of a hangup seeing the stats at the end of a run of ytdl-sub with how deleted videos where counted.
All I have done is make the total number of deleted videos negative (* -1) as well to be in line with the number of deleted videos for each subscription.

Make total delete videos in Total stats be negative

---

src/ytdl_sub/utils/chapters.py
tests/unit/utils/test_chapters.py

Hey there!
I've noticed that ytdl-sub throws an error when duplicate timestamps are found in its check for ascending order. Makes total sense for albums where you only have one track at a time, but I've found user-submitted timestamps for DJ sets sometimes feature these. For example, the top timestamp comment under [this video](https://www.youtube.com/watch?v=AEld3R_MRb4).
This pull request adds support for these duplicate timestamps by combining them into one with a delimiter in the timestamp title to split them up. I can change the delimiter if preferred, but it seemed like a good obvious one.
To find duplicates, I added a comparison to the last added Timestamp. If they match, the last added title is appended with the delimiter and the duplicate timestamp title. The duplicate's …

Support duplicate timestamps by merging into single timestamp

---

.github/workflows/release.yaml

Update release action to build aarch64 executable in arm64 runner.
Fixes [#1177](https://github.com/jmbannon/ytdl-sub/issues/1177)

Update release workflow to build aarch64 executable correctly

---

docker/root/custom-cont-init.d/defaults

Closes
- https://github.com/jmbannon/ytdl-sub/issues/1200
- Runs in the background now
- https://github.com/jmbannon/ytdl-sub/issues/1201
- Was not running as user `abc`, now it is
- https://github.com/jmbannon/ytdl-sub/issues/1202
- Due to reading stdout and tail of hidden log file. Should only tail from hidden log file now
Will leave crontab as-is if no CRON_SCHEDULE is specified

[DOCKER] Fix various cron issues

---

src/ytdl_sub/prebuilt_presets/tv_show/tv_show_by_date.yaml
src/ytdl_sub/prebuilt_presets/tv_show/tv_show_collection.yaml
tests/unit/prebuilt_presets/test_tv_show_by_date.py
tests/unit/prebuilt_presets/test_tv_show_collection.py

Dont let users supply `url` for TV Show Collection presets, or `s01_url` for TV Show by Date presets.

[FEATURE] Throw more actionable error if users supply the wrong type of url for TV show presets

---

docs/source/faq/index.rst

Added two items into faq page describing how to 
prevent creation of NFO files and downloading images

[DOCS] Add faq about disabling parts of presets to address #506

---

docs/source/config_reference/plugins.rst
docs/source/config_reference/scripting/entry_variables.rst
src/ytdl_sub/config/preset_options.py
src/ytdl_sub/config/validators/variable_validation.py
src/ytdl_sub/entries/script/variable_definitions.py
src/ytdl_sub/subscriptions/base_subscription.py
src/ytdl_sub/subscriptions/subscription_download.py
src/ytdl_sub/validators/string_formatter_validators.py
src/ytdl_sub/ytdl_additions/enhanced_download_archive.py
tests/integration/plugins/test_output_options.py

Implements https://github.com/jmbannon/ytdl-sub/issues/1182
Adds the ability to change the `keep_files_date_eval` (traditionally upload_date_standardized) to any date, so long as its in the form of YYYY-MM-DD.
Will be able to use this to have episodes named and maintained with release_date instead of upload_date.

[FEATURE] Ability to customize date used for deleting old files

---

docs/source/faq/index.rst
docs/source/guides/getting_started/index.rst
docs/source/guides/getting_started/quick_start.rst

Capture the method I used to force re-downloading previously archived entries as [detailed in Discord and confirmed by @jmbannon](https://discord.com/channels/994270357957648404/994270357957648408/1406876595364560970).

[DOCS] FAQ: How to force re-downloading an entry

---

docs/source/config_reference/scripting/static_variables.rst
docs/source/guides/getting_started/index.rst
docs/source/prebuilt_presets/music.rst
src/ytdl_sub/entries/variables/override_variables.py

This is another change that touches the generated docs, so after finishing my writing, I copied the change to `./docs/source/config_reference/scripting/static_variables.rst` into the corresponding docstring in
`./src/ytdl_sub/entries/variables/override_variables.py` and formatted it as a docstring. Then I ran:
$ REGENERATE_DOCS=1 tox exec -e "py" -- pytest tests/unit/docgen/test_docgen.py
But all that did was revert the changes to
`./docs/source/config_reference/scripting/static_variables.rst`. IOW, it did *not* update the rST from the changed docstring.

[DOCS] refs: Clarify the = YAML key prefix

---

docker/root/custom-cont-init.d/defaults

I'm not actually sure this is needed or correct and I haven't tested it, but just pushing a commit was an easy way to demonstrate my question.
If I'm reading correctly the `/config/.cron_wrapper` script generated by starting the container, then the `stderr` output of the wrapped script will *not* be included in `/config/.cron.log` and will essentially be lost. Am I correct in that?

fix(docker): Missing cron script stderr output

---

docs/source/config_reference/scripting/scripting_functions.rst
docs/source/debugging.rst
docs/source/faq/index.rst
docs/source/guides/development/index.rst
docs/source/index.rst
src/ytdl_sub/script/functions/print_functions.py

Reconcile the various debugging hints throughout the documentation and integrate into a central debugging page. Includes clarification of the roles of ytdl-sub, yt-dlp, and external services. Also adds cross references to the relevant bits across the docs.

[DOCS] debug: Clarify debugging, support, reporting

---

src/ytdl_sub/config/plugin/plugin.py
src/ytdl_sub/config/plugin/plugin_mapping.py
src/ytdl_sub/config/plugin/plugin_operation.py
src/ytdl_sub/plugins/throttle_protection.py
src/ytdl_sub/subscriptions/subscription_download.py

Closes https://github.com/jmbannon/ytdl-sub/issues/1294
Applies entry sleep per download *after* the download is fully complete and moved to the output folder.

[FEATURE] Apply entry throttle protection sleep post-completion

---

.readthedocs.yaml
Makefile
docs/source/usage.rst

I figured out why I kept getting warnings for broken Sphinx cross-refs *after* the
changes that caused them have already been merged, changes I know I ran `$ make docs`
for before pushing. The issue is that by default Sphinx only builds changed files for
faster iterations while editing, but it only catches broken cross-refs when it builds
files. So if changing, for example, a section name in one page that is referenced from
another page that you do *not* change, then the warning will be missed until something
changes that other page, such as a pull or rebase.
I considered adding a separate `./Makefile` target for incremental builds
in the inner loop of making changes. But I opted to just remove the `--write-all` CLI
option locally while editing in the inner loop, because the uncommitted …

[DEV] docs: Sphinx stale cross refs false success

---

src/ytdl_sub/prebuilt_presets/helpers/throttle_protection.yaml
tests/integration/plugins/test_throttle_protection.py

```
Resolution assert is enabled, will fail on low-quality video downloads and presume throttle. Disable using the override variable `enable_resolution_assert: False
```
Spams during the initialization phase. Ideally, we should only print this once the subscription has begun downloading. Perhaps via a `print` plugin? Either way, set this to debug log level.

[BACKEND] Make resolution print debug-level

---

docker/root/defaults/config.yaml
docker/root/defaults/subscriptions.yaml
docs/source/guides/getting_started/first_config.rst
src/ytdl_sub/config/defaults.py
src/ytdl_sub/utils/file_lock.py

Changes documentation and default configs to use the `/tv_shows` default path shown in the docker compose setup.
Also changes working directory and file lock directory to not be in /tmp, which often causes permission issues.

[DOCKER] Make default paths same as docker defaults

---

docs/source/faq/index.rst
docs/source/prebuilt_presets/helpers.rst
src/ytdl_sub/prebuilt_presets/helpers/throttle_protection.yaml
tests/integration/plugins/test_throttle_protection.py

Closes https://github.com/jmbannon/ytdl-sub/issues/1313
Adds `resolution_assert_ignore_titles` variable to be able to ignore specific videos in a subscription where 360p is suspected to be the only option.
Ideally, it would be nice if ytdl-sub could determine whether 360p is actually the only resolution or not automatically, and download if it's true. We need to do more research to determine if this is possible.
In the meantime, the above variable should help manually get around this. Usage:
```
"~My Subscription":
url: "https://youtube.com/@channel"
resolution_assert_ignore_titles:
- "This 360p Video Title"
```

[FEATURE] resolution_assert_ignore_titles to ignore specific low-resolution videos

---

docker/Dockerfile

Closes https://github.com/jmbannon/ytdl-sub/issues/1346
Keeps pip in the image to be able to update yt-dlp

[DOCKER] Do not remove pip for headless image
