.github/workflows/build_lint_test.yaml, tools/docs, tools/linter, tools/test
https://github.com/jmbannon/ytdl-sub/issues/11
=> Add github workflows for tests

.github/workflows/build_lint_test.yaml, examples/kodi_tv_shows_config.yaml, pyproject.toml, setup.cfg, src/ytdl_sub/plugins/nfo_tags.py, src/ytdl_sub/plugins/output_directory_nfo_tags.py, tests/__init__.py, tests/e2e/expected_download.py, tests/e2e/youtube/test_channel_as_kodi_tv_show.py, tools/test
https://github.com/jmbannon/ytdl-sub/issues/3
Adds the first e2e test which downloads my old minecraft YT channel and formats it as a TV show for kodi to consume
=> Add channel as kodi tv show e2e test

src/ytdl_sub/config/subscription.py, src/ytdl_sub/downloaders/youtube_downloader.py, src/ytdl_sub/logging/__init__.py, src/ytdl_sub/main.py, src/ytdl_sub/plugins/music_tags.py, src/ytdl_sub/plugins/plugin.py, src/ytdl_sub/utils/logger.py, src/ytdl_sub/ytdl_additions/enhanced_download_archive.py
https://github.com/jmbannon/ytdl-sub/issues/4 Still needs configuring but at least it will prevent a pile-up of prints to update
=> Create logger class, use it in favor of prints

examples/kodi_music_videos_config.yaml, examples/kodi_music_videos_subscriptions.yaml, src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/downloaders/youtube_downloader.py, src/ytdl_sub/entries/variables/youtube_variables.py, src/ytdl_sub/entries/youtube.py, subscriptions.yaml
Also add playlist example and simplify the info json reading logic
=> Add playlist_index and playlist_size to Youtube playlist videos

README.md, docs/conf.py, docs/config.rst, docs/index.rst, examples/kodi_tv_shows_subscriptions.yaml, src/ytdl_sub/config/preset_options.py, src/ytdl_sub/downloaders/soundcloud_downloader.py, src/ytdl_sub/downloaders/youtube_downloader.py, src/ytdl_sub/entries/variables/entry_variables.py, src/ytdl_sub/plugins/music_tags.py, src/ytdl_sub/plugins/nfo_tags.py, src/ytdl_sub/plugins/output_directory_nfo_tags.py, src/ytdl_sub/subscriptions/subscription.py, src/ytdl_sub/validators/string_datetime.py, src/ytdl_sub/validators/string_formatter_validators.py, tests/e2e/youtube/test_channel_as_kodi_tv_show.py
https://github.com/jmbannon/ytdl-sub/issues/1
Nearly the entire app is documented at this point
=> Add documentation for plugins + improve docs overall

docs/config.rst, docs/faq.rst, docs/index.rst
https://github.com/jmbannon/ytdl-sub/issues/2
=> Add FAQ and how to dl age-restricted vids

config.yaml, src/ytdl_sub/main.py, src/ytdl_sub/plugins/plugin.py, src/ytdl_sub/subscriptions/subscription.py
Fixes both https://github.com/jmbannon/ytdl-sub/issues/37 and https://github.com/jmbannon/ytdl-sub/issues/29
=> Fix error when maintain_download_archive=False, improve error message

config.yaml, docker/Dockerfile, src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/main.py, src/ytdl_sub/plugins/plugin.py, src/ytdl_sub/subscriptions/subscription.py
Fix some errors I encountered when trying to download a music vid. See commit messages for more details
=> ytdl-sub dl --youtube.video bugfixes

src/ytdl_sub/entries/variables/entry_variables.py, src/ytdl_sub/entries/variables/youtube_variables.py, tests/unit/entries/conftest.py, tests/unit/entries/test_youtube_entries.py
https://github.com/jmbannon/ytdl-sub/issues/32
https://github.com/jmbannon/ytdl-sub/issues/30
and a few more
=> Add more source variables

src/ytdl_sub/cli/main_args_parser.py, src/ytdl_sub/config/config_file.py, src/ytdl_sub/config/preset.py, src/ytdl_sub/utils/exceptions.py, src/ytdl_sub/utils/yaml.py, tests/unit/utils/test_yaml.py
Fix `ytdl-sub sub` errors and add YAML file error handling
https://github.com/jmbannon/ytdl-sub/issues/44
https://github.com/jmbannon/ytdl-sub/issues/31
=> Yaml error handling

examples/kodi_music_videos_config.yaml, tests/e2e/conftest.py, tests/e2e/youtube/test_channel_as_kodi_tv_show.py, tests/e2e/youtube/test_playlist_as_kodi_music_videos.py
https://github.com/jmbannon/ytdl-sub/issues/3
=> Tests for music video (YT vid + playlist) download

src/ytdl_sub/cli/download_args_parser.py, src/ytdl_sub/config/config_file.py, src/ytdl_sub/main.py, tests/unit/cli/test_download_args_parser.py
https://github.com/jmbannon/ytdl-sub/issues/66
=> Add aliases for `ytdl-sub dl`

Makefile, src/ytdl_sub/cli/main_args_parser.py, src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/main.py, src/ytdl_sub/utils/logger.py, tests/unit/main/test_main.py, tests/unit/utils/test_logger.py
https://github.com/jmbannon/ytdl-sub/issues/52
=> Configurable log levels

docker/Dockerfile, docker/root/defaults/config.yaml, docs/config.rst, examples/kodi_music_videos_config.yaml, examples/kodi_tv_shows_config.yaml, examples/soundcloud_discography_config.yaml, src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/downloaders/soundcloud_downloader.py, src/ytdl_sub/downloaders/youtube_downloader.py, tests/conftest.py, tests/e2e/youtube/test_channel_as_kodi_tv_show.py, tests/e2e/youtube/test_playlist_as_kodi_music_videos.py
https://github.com/jmbannon/ytdl-sub/issues/53
=> `ytdl_options` defaults for each download strategy

.github/workflows/ci.yaml, docs/config.rst, src/ytdl_sub/config/preset_class_mappings.py, src/ytdl_sub/downloaders/youtube/split_video.py, src/ytdl_sub/utils/ffmpeg.py, tests/e2e/youtube/test_split_video.py
https://github.com/jmbannon/ytdl-sub/issues/63
=> youtube.download_strategy split_video

docs/config.rst, examples/kodi_music_videos_config.yaml, setup.cfg, src/ytdl_sub/config/config_file.py, src/ytdl_sub/config/preset_class_mappings.py, src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/downloaders/youtube/merge_playlist.py, src/ytdl_sub/downloaders/youtube/split_video.py, src/ytdl_sub/entries/variables/youtube_variables.py, src/ytdl_sub/subscriptions/subscription.py, src/ytdl_sub/utils/chapters.py, src/ytdl_sub/utils/ffmpeg.py, src/ytdl_sub/utils/thumbnail.py, tests/e2e/expected_download.py, tests/e2e/youtube/test_channel_as_kodi_tv_show.py, tests/e2e/youtube/test_merge_playlist.py, tests/e2e/youtube/test_playlist_as_kodi_music_videos.py, tests/unit/utils/test_chapters.py
https://github.com/jmbannon/ytdl-sub/issues/64
=> Add youtube.download_strategy: "merge_playlist"

src/ytdl_sub/config/preset.py, src/ytdl_sub/entries/variables/entry_variables.py, src/ytdl_sub/validators/string_formatter_validators.py, tests/unit/config/test_preset.py, tests/unit/validators/test_string_formatter_validator.py
Makes it so any variable formatting errors error immediately before any downloading begins
=> Validate all preset StringFormatValidators on init

src/ytdl_sub/ytdl_additions/enhanced_download_archive.py, tests/e2e/youtube/test_channel_as_kodi_tv_show.py
https://github.com/jmbannon/ytdl-sub/issues/81
=> Fix error where download archive does not exist from no downloads

docs/config.rst, src/ytdl_sub/config/preset_class_mappings.py, src/ytdl_sub/downloaders/soundcloud/abc.py, src/ytdl_sub/downloaders/soundcloud/albums_and_singles.py, src/ytdl_sub/downloaders/youtube/abc.py, src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/downloaders/youtube/merge_playlist.py, src/ytdl_sub/downloaders/youtube/playlist.py, src/ytdl_sub/downloaders/youtube/split_video.py, src/ytdl_sub/downloaders/youtube/video.py
Humble refactoring to smaller, separate files for each downloader
=> [REFACTOR] Move downloaders to separate files

README.md, docs/config.rst, docs/faq.rst, docs/getting_started.rst, examples/kodi_music_videos_config.yaml, examples/kodi_tv_shows_config.yaml
Docs for how to set up a cron job
=> [DOCS] Automated download via cron docs

src/ytdl_sub/plugins/plugin.py, src/ytdl_sub/validators/regex_validator.py, src/ytdl_sub/validators/validators.py, tests/unit/validators/test_regex_validator.py
Validators for:
https://github.com/jmbannon/ytdl-sub/issues/62
https://github.com/jmbannon/ytdl-sub/issues/28
=> [BACKEND] Add regex validators

src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/subscriptions/subscription.py, tests/e2e/youtube/test_channel_as_kodi_tv_show.py
https://github.com/jmbannon/ytdl-sub/issues/96
=> [FEATURE] `download_individually` for Youtube channel

src/ytdl_sub/downloaders/youtube/playlist.py, tests/e2e/youtube/test_playlist_as_kodi_music_videos.py
https://github.com/jmbannon/ytdl-sub/issues/96
=> [FEATURE] `download_individually` for youtube playlists

src/ytdl_sub/entries/variables/entry_variables.py, src/ytdl_sub/entries/variables/youtube_variables.py, tests/unit/entries/conftest.py, tests/unit/entries/test_youtube_entries.py
https://github.com/jmbannon/ytdl-sub/issues/113
=> [BUGFIX] Remove description from Soundcloud source variables

src/ytdl_sub/downloaders/soundcloud/albums_and_singles.py
Do not assume all album tracks are also tracks
=> [BUGFIX] Fix missing Soundcloud album tracks

src/ytdl_sub/entries/entry.py, src/ytdl_sub/entries/soundcloud.py, src/ytdl_sub/entries/youtube.py, src/ytdl_sub/subscriptions/subscription.py, src/ytdl_sub/thread/log_entries_downloaded_listener.py
https://github.com/jmbannon/ytdl-sub/issues/111
=> [BACKEND] info log download titles as they appear

src/ytdl_sub/downloaders/soundcloud/albums_and_singles.py, src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/downloaders/youtube/playlist.py, tests/e2e/conftest.py, tests/e2e/soundcloud/test_soundcloud_discography.py
https://github.com/jmbannon/ytdl-sub/issues/112
Do not include the arg because there is no good reason to not download individually
=> [BACKEND] Download and process Soundcloud tracks individually

src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/downloaders/youtube/playlist.py, tests/e2e/youtube/test_channel_as_kodi_tv_show.py, tests/e2e/youtube/test_playlist_as_kodi_music_videos.py
From youtube channel + playlist download strategies. Remove the option to choose not to (sorry people using this on the latest docker image who have that set).
=> [BACKEND] Always download individually when possible

src/ytdl_sub/cli/download_args_parser.py, src/ytdl_sub/utils/exceptions.py, tests/unit/cli/test_download_args_parser.py
Fixes #103
`ytdl-sub dl` now supports the list
=> List support for ytdl-sub dl (#103)

src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/downloaders/soundcloud/albums_and_singles.py, src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/downloaders/youtube/playlist.py, src/ytdl_sub/entries/soundcloud.py, src/ytdl_sub/subscriptions/subscription.py, src/ytdl_sub/thread/log_entries_downloaded_listener.py, src/ytdl_sub/utils/ffmpeg.py, tests/e2e/youtube/test_channel_as_kodi_tv_show.py, tests/e2e/youtube/test_playlist_as_kodi_music_videos.py
Fixes https://github.com/jmbannon/ytdl-sub/issues/118 and makes info prints more robust
=> [FEATURE] Improve info logger messages

src/ytdl_sub/cli/download_args_parser.py
Fixes PR https://github.com/jmbannon/ytdl-sub/pull/125
=> [BACKEND] Do the match and extraction in one function (#103)

src/ytdl_sub/downloaders/youtube/video.py, tests/e2e/conftest.py, tests/e2e/resources/transaction_log_summaries/youtube/test_video_with_chapter_timestamps.txt, tests/e2e/youtube/test_playlist.py, tests/e2e/youtube/test_split_video.py, tests/e2e/youtube/test_video.py
Add `chapter_timestamps` optional arg to Youtube video download strategy
=> [FEATURE] Add chapters to YouTube videos via timestamps file

src/ytdl_sub/downloaders/youtube/merge_playlist.py, tests/e2e/resources/transaction_log_summaries/youtube/test_merge_playlist.txt, tests/e2e/youtube/test_merge_playlist.py
https://github.com/jmbannon/ytdl-sub/issues/135
=> [BUG] Fix merge_playlist ordering

src/ytdl_sub/cli/download_args_parser.py, src/ytdl_sub/cli/main.py, src/ytdl_sub/cli/main_args_parser.py, tests/unit/cli/test_download_args_parser.py
https://github.com/jmbannon/ytdl-sub/issues/110
=> [BUG] Prevent ytdl-sub args being specified as `dl` args

src/ytdl_sub/downloaders/youtube/channel.py
https://github.com/jmbannon/ytdl-sub/issues/140
=> [BUG] Fix channel artwork error if not specified

src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/downloaders/youtube/playlist.py
https://github.com/jmbannon/ytdl-sub/issues/143
=> [DOCS] Remove download_individually params from readthedocs

docs/config.rst, src/ytdl_sub/entries/variables/entry_variables.py, src/ytdl_sub/entries/variables/soundcloud_variables.py, src/ytdl_sub/entries/variables/youtube_variables.py
https://github.com/jmbannon/ytdl-sub/issues/85
=> [DOCS] Clean up source variable readthedocs section

src/ytdl_sub/plugins/nfo_tags.py, src/ytdl_sub/plugins/output_directory_nfo_tags.py, src/ytdl_sub/utils/xml.py, src/ytdl_sub/validators/url_validator.py, tests/e2e/plugins/test_nfo_tags.py, tests/e2e/resources/transaction_log_summaries/plugins/test_kodi_safe_xml.txt, tests/unit/validators/test_url_validator.py
https://github.com/jmbannon/ytdl-sub/issues/156
https://github.com/jmbannon/ytdl-sub/issues/153
=> [FEATURE+BUGFIX] Add `kodi_safe` arg for NFO plugins, support YT shorts

src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/downloaders/soundcloud/albums_and_singles.py, src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/downloaders/youtube/playlist.py
https://github.com/jmbannon/ytdl-sub/issues/148
https://github.com/jmbannon/ytdl-sub/issues/142
=> [BACKEND] Download descending, process ascending for YT channels and playlists

src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/downloaders/youtube/playlist.py
Actually ensures https://github.com/jmbannon/ytdl-sub/issues/142
=> [FOLLOWUP] Actually process YT channels and playlists ascending

src/ytdl_sub/cli/main.py, src/ytdl_sub/utils/file_handler.py, src/ytdl_sub/ytdl_additions/enhanced_download_archive.py, tests/conftest.py, tests/e2e/conftest.py, tests/e2e/youtube/test_playlist.py, tests/e2e/youtube/test_video.py, tests/unit/utils/test_yaml.py
https://github.com/jmbannon/ytdl-sub/issues/145
=> [BACKEND] Do not write download archive file if no files changed

docs/config.rst, src/ytdl_sub/config/preset_class_mappings.py, src/ytdl_sub/downloaders/youtube/merge_playlist.py, src/ytdl_sub/downloaders/youtube/video.py, src/ytdl_sub/plugins/video_tags.py, src/ytdl_sub/utils/ffmpeg.py, tests/e2e/plugins/test_subtitles.py, tests/e2e/resources/expected_downloads_summaries/plugins/test_subtitles_tags_chapters.json, tests/e2e/resources/expected_downloads_summaries/youtube/test_video.json, tests/e2e/resources/expected_downloads_summaries/youtube/test_video_with_chapter_timestamps.json, tests/e2e/resources/transaction_log_summaries/plugins/test_subtitles_tags_chapters.txt, tests/e2e/resources/transaction_log_summaries/youtube/test_video.txt, tests/e2e/resources/transaction_log_summaries/youtube/test_video_with_chapter_timestamps.txt, tests/e2e/youtube/test_video.py
https://github.com/jmbannon/ytdl-sub/issues/168
=> [FEATURE] Video tags plugin to embed metadata into video files

src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/downloaders/youtube/playlist.py, src/ytdl_sub/plugins/subtitles.py, tests/e2e/resources/expected_downloads_summaries/youtube/test_channel_full.json, tests/e2e/resources/expected_downloads_summaries/youtube/test_channel_recent.json, tests/e2e/resources/expected_downloads_summaries/youtube/test_channel_rolling_recent.json, tests/e2e/resources/transaction_log_summaries/youtube/test_channel_full.txt, tests/e2e/resources/transaction_log_summaries/youtube/test_channel_recent.txt, tests/e2e/youtube/test_channel.py, tests/e2e/youtube/test_playlist.py
https://github.com/jmbannon/ytdl-sub/issues/174
When doing the actual download, download it as a single video instead of a subset of the channel/playlist
=> [BUGFIX] Subtitles for channel + playlist downloads

docs/config.rst, examples/youtube_extract_and_tag_audio.yaml, src/ytdl_sub/config/preset_class_mappings.py, src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/downloaders/youtube/playlist.py, src/ytdl_sub/entries/entry.py, src/ytdl_sub/plugins/audio_extract.py, src/ytdl_sub/subscriptions/subscription_ytdl_options.py, src/ytdl_sub/validators/audo_codec_validator.py, src/ytdl_sub/validators/validators.py, tests/e2e/conftest.py, tests/e2e/plugins/test_audio_extract.py, tests/e2e/resources/expected_downloads_summaries/plugins/test_audio_extract_playlist.json, tests/e2e/resources/expected_downloads_summaries/plugins/test_audio_extract_single.json, tests/e2e/resources/transaction_log_summaries/plugins/test_audio_extract_playlist.txt, tests/e2e/resources/transaction_log_summaries/plugins/test_audio_extract_single.txt
https://github.com/jmbannon/ytdl-sub/issues/175
=> [FEATURE] Audio extract plugin

src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/downloaders/youtube/playlist.py
https://github.com/jmbannon/ytdl-sub/issues/205
=> [BUGFIX] Handle `source_uploader` when it is empty

src/ytdl_sub/downloaders/downloader.py
https://github.com/jmbannon/ytdl-sub/issues/190
=> [BUGFIX] Fix extract info with retry issue with deleting download archive

src/ytdl_sub/downloaders/youtube/channel.py, src/ytdl_sub/utils/retry.py, src/ytdl_sub/utils/thumbnail.py, tests/e2e/youtube/test_channel.py
Fix for https://github.com/jmbannon/ytdl-sub/issues/211, https://github.com/jmbannon/ytdl-sub/issues/214, https://github.com/jmbannon/ytdl-sub/issues/212
=> [BUGFIX] Retry channel image downloads, continue if it fails

src/ytdl_sub/cli/main.py, tests/unit/cli/test_working_directory_lock.py
https://github.com/jmbannon/ytdl-sub/issues/154
=> [BACKEND] File lock working directory to prevent multiple instances from running

src/ytdl_sub/entries/base_entry.py, src/ytdl_sub/entries/entry.py, src/ytdl_sub/entries/soundcloud.py, src/ytdl_sub/entries/variables/entry_variables.py, src/ytdl_sub/entries/youtube.py
Moving entry functions to more appropriate places
=> [BACKEND] Refactor Entry

src/ytdl_sub/entries/base_entry.py, src/ytdl_sub/entries/variables/youtube_variables.py, tests/unit/entries/conftest.py
https://github.com/jmbannon/ytdl-sub/issues/215
=> [BUGFIX] Fix source vars containing variable-like syntax

src/ytdl_sub/config/preset_class_mappings.py, src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/downloaders/generic/collection.py, src/ytdl_sub/downloaders/generic/collection_validator.py, src/ytdl_sub/downloaders/generic/source.py, src/ytdl_sub/downloaders/youtube/video.py
Hidden w/out docs for now, but usable
=> [BACKEND] `generic.source` download strategy

src/ytdl_sub/cli/main.py
https://github.com/jmbannon/ytdl-sub/issues/286
=> [BACKEND] Make dry-run log message

src/ytdl_sub/config/preset_class_mappings.py, src/ytdl_sub/downloaders/generic/collection.py, src/ytdl_sub/downloaders/generic/collection_validator.py, src/ytdl_sub/downloaders/generic/source.py, src/ytdl_sub/prebuilt_presets/music_videos/kodi_music_videos.yaml, src/ytdl_sub/prebuilt_presets/tv_show/tv_show.yaml, src/ytdl_sub/prebuilt_presets/tv_show/tv_show_collection.yaml, tests/unit/config/test_config_file.py
eventually just have one with no `download_strategy`
=> [REFACTOR] Rename `generic` download source to `download`

.github/workflows/package.yaml, docker/root/defaults/config.yaml, docker/root/defaults/subscriptions.yaml, docker/root/etc/cont-init.d/30-config
https://github.com/jmbannon/ytdl-sub/issues/93
=> [BACKEND] Update docker container to have latest examples

src/ytdl_sub/prebuilt_presets/tv_show/tv_show.yaml
https://github.com/jmbannon/ytdl-sub/issues/280
=> [BACKEND] Have Plex TV show preset try to download mp4

docker/Dockerfile
This reverts commit 52b01308882dfa413dfe0f2b91990f7eae8637ac.
=> Revert "[BACKEND] Use latest ffmpeg (#327)"

docker/Dockerfile
This reverts commit 7b43aa904b5df32e6438b312f5d72673179d5ae5.
=> Revert "[DOCKER] Use alpine-3.16, update ffmpeg (#330)"

examples/music_audio_from_videos.yaml, src/ytdl_sub/plugins/music_tags.py, src/ytdl_sub/subscriptions/subscription_ytdl_options.py, src/ytdl_sub/utils/thumbnail.py, tests/e2e/plugins/test_audio_extract.py, tests/resources/expected_downloads_summaries/plugins/test_audio_extract_single.json, tests/resources/transaction_log_summaries/plugins/test_audio_extract_single.txt
https://github.com/jmbannon/ytdl-sub/issues/343
=> [FEATURE] Embed thumbnails into audio files as cover art

docker/Dockerfile, src/ytdl_sub/plugins/music_tags.py, tests/e2e/plugins/test_audio_extract.py, tests/resources/expected_downloads_summaries/plugins/test_audio_extract_playlist.json, tests/resources/expected_downloads_summaries/plugins/test_audio_extract_single.json, tests/resources/transaction_log_summaries/plugins/test_audio_extract_single.txt
https://github.com/jmbannon/ytdl-sub/issues/120
docker issue fix reference: https://gitlab.alpinelinux.org/alpine/aports/-/issues/14098
=> [FEATURE] Add mp3 id3v2.4 multi-tag support

docker/Dockerfile
https://github.com/jmbannon/ytdl-sub/issues/357
=> [DOCKER][BUGFIX] Fix ffmpeg

src/ytdl_sub/entries/entry.py, src/ytdl_sub/plugins/file_convert.py, tests/e2e/plugins/test_file_convert.py, tests/expected_transaction_log.py, tests/resources/expected_downloads_summaries/plugins/file_convert/output_custom_ffmpeg.json, tests/resources/transaction_log_summaries/plugins/file_convert/output_custom_ffmpeg.txt
https://github.com/jmbannon/ytdl-sub/issues/352
=> [FEATURE] Add custom ffmpeg post-processing

docs/config.rst, src/ytdl_sub/config/preset_class_mappings.py, src/ytdl_sub/plugins/match_filters.py, src/ytdl_sub/subscriptions/subscription_ytdl_options.py, tests/e2e/plugins/test_match_filters.py
https://github.com/jmbannon/ytdl-sub/issues/314
workaround for https://github.com/jmbannon/ytdl-sub/issues/219
=> [FEATURE] Match filters plugin

src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/entries/entry_parent.py
https://github.com/jmbannon/ytdl-sub/issues/353
=> [FEATURE] Add better download progress

src/ytdl_sub/cli/main.py, src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/entries/base_entry.py, src/ytdl_sub/entries/entry_parent.py
https://github.com/jmbannon/ytdl-sub/issues/374
=> [BACKEND] Reduce memory footprint

src/ytdl_sub/downloaders/downloader.py, src/ytdl_sub/plugins/nfo_tags.py, src/ytdl_sub/plugins/subtitles.py, src/ytdl_sub/subscriptions/subscription_download.py, src/ytdl_sub/utils/file_handler.py, src/ytdl_sub/utils/thumbnail.py, src/ytdl_sub/ytdl_additions/enhanced_download_archive.py, tests/conftest.py, tests/e2e/conftest.py, tests/e2e/youtube/test_playlist.py, tests/unit/prebuilt_presets/conftest.py
https://github.com/jmbannon/ytdl-sub/issues/378
=> [BACKEND] Proactively clean working directory

src/ytdl_sub/entries/entry_parent.py, tests/resources/expected_downloads_summaries/plugins/chapters/test_chapters_from_comments.json
https://github.com/jmbannon/ytdl-sub/issues/391
=> [BUGFIX] Fix entry missing __contains__ function

src/ytdl_sub/plugins/regex.py
https://github.com/jmbannon/ytdl-sub/issues/371
=> [DOCS] Document additional backslash for regex

src/ytdl_sub/plugins/music_tags.py, src/ytdl_sub/plugins/plugin.py, tests/e2e/plugins/test_music_tags.py
https://github.com/jmbannon/ytdl-sub/issues/399
=> [BACKEND] Better error message for music_tags recieving a video

src/ytdl_sub/entries/variables/entry_variables.py, tests/unit/entries/conftest.py
https://github.com/jmbannon/ytdl-sub/issues/394
=> [BACKEND] Add playlist_uploader_sanitized var

docker/Dockerfile, tests/e2e/plugins/test_chapters.py
https://github.com/jmbannon/ytdl-sub/issues/438
credit to @wjbridge ;)
=> [DOCKER] Upgrade ffmpeg, add phantomjs

src/ytdl_sub/validators/string_datetime.py
https://github.com/jmbannon/ytdl-sub/issues/432
=> [DOCS] Lowest date_range granularity is day

src/ytdl_sub/downloaders/downloader.py, tests/conftest.py, tests/e2e/plugins/test_date_range.py, tests/e2e/youtube/test_playlist.py
https://github.com/jmbannon/ytdl-sub/issues/431
=> [BACKEND] More verbose logging when breaking

src/ytdl_sub/config/preset_options.py
https://github.com/jmbannon/ytdl-sub/issues/428
=> [DOCS] Automatic sanitized override variable docs

docs/presets.rst
https://github.com/jmbannon/ytdl-sub/issues/434
=> [DOCS] Add link to prebuilt preset definitions

src/ytdl_sub/cli/main.py, src/ytdl_sub/config/config_validator.py
https://github.com/jmbannon/ytdl-sub/issues/423
=> [BACKEND] File lock directory config parameter

docs/presets.rst, src/ytdl_sub/prebuilt_presets/tv_show/tv_show_collection.yaml
https://github.com/jmbannon/ytdl-sub/issues/430
=> [BACKEND] Add more collection seasons

src/ytdl_sub/cli/main.py, src/ytdl_sub/utils/logger.py, tests/unit/utils/test_logger.py
https://github.com/jmbannon/ytdl-sub/issues/380
=> [BACKEND] Reset debug log on every subscription

src/ytdl_sub/cli/main.py, src/ytdl_sub/cli/main_args_parser.py, src/ytdl_sub/main.py, tests/unit/utils/test_logger.py
https://github.com/jmbannon/ytdl-sub/issues/462
=> [BACKEND] Add --version arg

docs/usage.rst, src/ytdl_sub/cli/download_args_parser.py, src/ytdl_sub/cli/main.py, src/ytdl_sub/cli/main_args_parser.py, tests/expected_transaction_log.py, tests/unit/cli/test_download_args_parser.py, tests/unit/cli/test_main.py
https://github.com/jmbannon/ytdl-sub/issues/426
=> [BUGFIX] Fix global options not working after `sub`

docs/config.rst, src/ytdl_sub/cli/main.py, src/ytdl_sub/config/config_file.py, src/ytdl_sub/config/config_validator.py, src/ytdl_sub/main.py, src/ytdl_sub/utils/logger.py, tests/conftest.py, tests/e2e/conftest.py, tests/unit/cli/test_main.py, tests/unit/main/test_main.py, tests/unit/prebuilt_presets/conftest.py, tests/unit/utils/test_logger.py
https://github.com/jmbannon/ytdl-sub/issues/439
=> [FEATURE] Persisted subscription logs

docs/usage.rst, src/ytdl_sub/cli/main.py, src/ytdl_sub/cli/main_args_parser.py, tests/unit/cli/test_main.py
https://github.com/jmbannon/ytdl-sub/issues/288
=> [FEATURE] Ability to suppress or write transaction log to file

src/ytdl_sub/plugins/subtitles.py, src/ytdl_sub/utils/subtitles.py, src/ytdl_sub/validators/file_path_validators.py, tests/unit/validators/test_file_path_validators.py
https://github.com/jmbannon/ytdl-sub/issues/222
=> [BUGFIX] Handle truncating file names if too long

tests/e2e/plugins/test_subtitles.py
https://github.com/jmbannon/ytdl-sub/issues/522
=> [BACKEND] partial validate test for subtitle lang variable

src/ytdl_sub/entries/base_entry.py, src/ytdl_sub/entries/variables/kwargs.py, src/ytdl_sub/ytdl_additions/enhanced_download_archive.py, tests/e2e/bandcamp/test_bandcamp.py
https://github.com/jmbannon/ytdl-sub/issues/518
=> [BUGFIX] Fix extractor IDs in yt-dlp download archive

docker/Dockerfile, setup.cfg, src/ytdl_sub/__init__.py, src/ytdl_sub/validators/file_path_validators.py, tests/unit/validators/test_file_path_validators.py
https://github.com/jmbannon/ytdl-sub/issues/555
=> [BUGFIX] File name too long with -thumb.jpg

src/ytdl_sub/config/config_file.py, src/ytdl_sub/config/config_validator.py, src/ytdl_sub/config/defaults.py, src/ytdl_sub/validators/file_path_validators.py, src/ytdl_sub/validators/validators.py, tests/unit/validators/test_file_path_validators.py
https://github.com/jmbannon/ytdl-sub/issues/561
=> [FEATURE] Configurable file_name_max_bytes

src/ytdl_sub/config/preset.py, tests/unit/config/test_config_file.py
https://github.com/jmbannon/ytdl-sub/issues/444
=> [BUGFIX] Read parent preset download strategy when partial validating

src/ytdl_sub/entries/variables/entry_variables.py, tests/unit/entries/conftest.py
=> [FEATURE] `creator_sanitized` source variable

src/ytdl_sub/utils/chapters.py
https://github.com/jmbannon/ytdl-sub/issues/481
Was able to return one line's worth of chapters. Should require >3 lines
=> [BUGFIX] Fix parsing chapters from comments

src/ytdl_sub/utils/chapters.py
https://github.com/jmbannon/ytdl-sub/issues/481
=> [BUGFIX] Fix splitting chapters extracted from comments

docs/config.rst, src/ytdl_sub/plugins/regex.py, tests/e2e/plugins/test_regex.py, tests/resources/transaction_log_summaries/plugins/test_regex_exclude.txt, tests/resources/transaction_log_summaries/plugins/test_regex_match_and_exclude.txt
https://github.com/jmbannon/ytdl-sub/issues/478
=> [FEATURE] `exclude` field in regex plugin

src/ytdl_sub/downloaders/ytdlp.py
https://github.com/jmbannon/ytdl-sub/issues/614
=> [BUGFIX] Add `check_formats` on download retry

src/ytdl_sub/plugins/match_filters.py
https://github.com/jmbannon/ytdl-sub/issues/621
=> [DOCS] Clean up match-filter plugin docs

src/ytdl_sub/utils/file_lock.py
https://github.com/jmbannon/ytdl-sub/issues/607
=> [DOCS] Actionable message for file lock errors

src/ytdl_sub/downloaders/url/validators.py
https://github.com/jmbannon/ytdl-sub/issues/573
=> [DOCS] Fix url + multi_url docs

docs/config.rst, src/ytdl_sub/subscriptions/subscription.py, tests/unit/config/test_subscription.py
https://github.com/jmbannon/ytdl-sub/issues/640
=> [FEATURE] Add `__value__` to subscription files to be able to create one-liner subs

docker/Dockerfile, docker/Dockerfile.ubuntu, setup.cfg
This reverts commit 3cbd07c9a4e0da81f129b8f30cfe4759a53ffb40.
=> Revert "[BACKEND] Update yt-dlp to latest commit (#655)"

src/ytdl_sub/utils/yaml.py, tests/unit/utils/test_yaml.py
https://github.com/jmbannon/ytdl-sub/issues/677
=> [BACKEND] Include yaml exception in error

.github/workflows/package-ubuntu.yaml, .github/workflows/package.yaml, .github/workflows/release.yaml
- Apply to docker, release, pypi
- proper syntax
=> [DEV] Fix release conditional

src/ytdl_sub/cli/main.py, src/ytdl_sub/config/config_file.py, src/ytdl_sub/utils/logger.py, tests/unit/main/test_main.py
https://github.com/jmbannon/ytdl-sub/issues/716
https://github.com/jmbannon/ytdl-sub/issues/715
Add more informative messages
=> [FEATURE] More verbose error logs when using ytdl-sub commands

src/ytdl_sub/plugins/regex.py
https://github.com/jmbannon/ytdl-sub/issues/647
=> [DOCS] Mention YAML single vs double quotes in regex docs

src/ytdl_sub/utils/logger.py, tests/unit/main/test_main.py
https://github.com/jmbannon/ytdl-sub/issues/720
=> [BACKEND] More explicit error message for PermissionError

.github/workflows/package-ubuntu.yaml, .github/workflows/package.yaml
https://github.com/jmbannon/ytdl-sub/issues/627
=> [DOCKER] Add version tag to all images

src/ytdl_sub/prebuilt_presets/helpers/players.yaml
https://github.com/jmbannon/ytdl-sub/issues/427
=> [BACKEND] Filter out upcoming videos and post-live streams by default

src/ytdl_sub/cli/entrypoint.py
https://github.com/jmbannon/ytdl-sub/issues/769
=> [BUGFIX] Prevent default config from eagerly validating

src/ytdl_sub/cli/entrypoint.py, src/ytdl_sub/cli/output_summary.py, src/ytdl_sub/cli/output_transaction_log.py, src/ytdl_sub/main.py, src/ytdl_sub/subscriptions/base_subscription.py, src/ytdl_sub/subscriptions/subscription_download.py, src/ytdl_sub/utils/logger.py, tests/e2e/conftest.py, tests/e2e/plugins/internal/test_view.py, tests/e2e/youtube/test_playlist.py, tests/e2e/youtube/test_video.py, tests/unit/cli/conftest.py, tests/unit/cli/test_entrypoint.py, tests/unit/cli/test_output_summary.py, tests/unit/cli/test_output_transaction_log.py, tests/unit/main/test_main.py, tests/unit/utils/test_logger.py
https://github.com/jmbannon/ytdl-sub/issues/766
https://github.com/jmbannon/ytdl-sub/issues/520
=> [FEATURE] Process all subscriptions even if one or more error

src/ytdl_sub/plugins/embed_thumbnail.py, src/ytdl_sub/plugins/filter_exclude.py, src/ytdl_sub/plugins/filter_include.py, src/ytdl_sub/plugins/match_filters.py, src/ytdl_sub/plugins/music_tags.py, src/ytdl_sub/plugins/video_tags.py
https://github.com/jmbannon/ytdl-sub/issues/852
=> [BACKEND] Info log for `filter_include` and `filter_exclude` plugins

src/ytdl_sub/downloaders/url/downloader.py, src/ytdl_sub/prebuilt_presets/helpers/url.yaml, src/ytdl_sub/prebuilt_presets/tv_show/tv_show_collection.yaml, tests/resources/expected_downloads_summaries/plugins/chapters/test_chapters_from_comments.json, tests/resources/expected_downloads_summaries/plugins/test_chapters_sb_and_embedded_subs.json, tests/resources/expected_downloads_summaries/youtube/test_playlist.json, tests/resources/expected_downloads_summaries/youtube/test_playlist_archive_migrated.json, tests/resources/transaction_log_summaries/youtube/test_playlist.txt
Implements https://github.com/jmbannon/ytdl-sub/issues/756
TV Show presets whose URL is a playlist will try to get the playlist uploader's poster and fanart.
=> [FEATURE] YouTube playlists to fetch playlist uploader's poster + fanart

src/ytdl_sub/config/validators/variable_validation.py, src/ytdl_sub/script/script.py, src/ytdl_sub/utils/scriptable.py, src/ytdl_sub/validators/string_formatter_validators.py, tests/e2e/youtube/test_video.py, tests/unit/config/test_preset.py
With the right functions, it was possible for subscription validation to raise a false-positive error. This should hopefully resolve that issue and give validation a small performance increase
=> [BUGFIX] Smarter subscription validation

docs/source/config_reference/plugins.rst, src/ytdl_sub/config/plugin/plugin.py, src/ytdl_sub/config/validators/options.py, src/ytdl_sub/plugins/audio_extract.py, src/ytdl_sub/plugins/chapters.py, src/ytdl_sub/plugins/date_range.py, src/ytdl_sub/plugins/file_convert.py, src/ytdl_sub/plugins/filter_exclude.py, src/ytdl_sub/plugins/filter_include.py, src/ytdl_sub/plugins/match_filters.py, src/ytdl_sub/plugins/nfo_tags.py, src/ytdl_sub/plugins/output_directory_nfo_tags.py, src/ytdl_sub/plugins/regex.py, src/ytdl_sub/plugins/subtitles.py, src/ytdl_sub/plugins/throttle_protection.py, src/ytdl_sub/plugins/video_tags.py, src/ytdl_sub/subscriptions/subscription_download.py, src/ytdl_sub/utils/script.py, src/ytdl_sub/validators/string_formatter_validators.py, tests/conftest.py, tests/unit/plugins/test_throttle_protection.py, tests/unit/utils/test_script_utils.py
For key/value-based plugins, add an `enable` field to make it easier for child presets to disable their functionality
=> [FEATURE] Toggleable plugin field `enable` for all dict-based plugins

docker/Dockerfile, src/ytdl_sub/entries/entry_parent.py
Fixes https://github.com/jmbannon/ytdl-sub/issues/908
=> [BUGFIX] Fix multiple top-level parents for linked VEVO YouTube channels

src/ytdl_sub/entries/base_entry.py
Fixes https://github.com/jmbannon/ytdl-sub/issues/910 , when yt-dlp sometimes returns a non-serializable LazyList
=> [BUGFIX] Handle case when yt-dlp returns LazyList

src/ytdl_sub/subscriptions/subscription_download.py, src/ytdl_sub/subscriptions/subscription_ytdl_options.py, src/ytdl_sub/utils/file_handler.py, src/ytdl_sub/ytdl_additions/enhanced_download_archive.py
Attempts to make writes to the download archive safer (https://github.com/jmbannon/ytdl-sub/issues/982)
=> [BUGFIX] Prevent corrupt writes to download archive

src/ytdl_sub/config/plugin/plugin_operation.py, src/ytdl_sub/config/validators/options.py, src/ytdl_sub/config/validators/variable_validation.py, src/ytdl_sub/downloaders/url/validators.py, src/ytdl_sub/plugins/chapters.py, src/ytdl_sub/plugins/split_by_chapters.py, src/ytdl_sub/plugins/subtitles.py, src/ytdl_sub/subscriptions/subscription_download.py, tests/unit/plugins/test_chapters.py, tests/unit/plugins/test_filter.py
Fixes https://github.com/jmbannon/ytdl-sub/issues/1071
=> [BUGFIX] Fix variable collision when disabling plugins

src/ytdl_sub/config/preset_options.py, src/ytdl_sub/downloaders/url/downloader.py, src/ytdl_sub/subscriptions/subscription_ytdl_options.py
Fixes a bug that messed up bilateral downloads from playlists
=> [BUGFIX] Materialize url-based ytdl-options 

docs/source/guides/install/docker.rst
Fixes https://github.com/jmbannon/ytdl-sub/issues/1093
=> [DOCS] Fix docker indents

src/ytdl_sub/script/parser.py, tests/unit/script/functions/test_string_functions.py, tests/unit/script/types/test_string.py
Fixes https://github.com/jmbannon/ytdl-sub/issues/1094
=> [FEATURE] Support newlines and tabs in strings

docs/source/guides/getting_started/advanced_configuration.rst
Fixes https://github.com/jmbannon/ytdl-sub/issues/1009
=> [DOCS] Fix preset key

docs/source/config_reference/scripting/scripting_functions.rst, src/ytdl_sub/script/functions/string_functions.py, src/ytdl_sub/script/parser.py, tests/unit/script/functions/test_string_functions.py, tests/unit/script/types/test_string.py
Fixes https://github.com/jmbannon/ytdl-sub/issues/1107
Changes solution to https://github.com/jmbannon/ytdl-sub/issues/1094
=> [BUGFIX] Move unescape parsing to separate function

docker/Dockerfile, docker/Dockerfile.gui, docker/Dockerfile.ubuntu
https://github.com/jmbannon/ytdl-sub/issues/1131
=> [DOCKER] Export SSL certs

src/ytdl_sub/cli/entrypoint.py, src/ytdl_sub/cli/output_summary.py, src/ytdl_sub/cli/parsers/main.py, src/ytdl_sub/config/config_validator.py, tests/unit/cli/test_output_summary.py
Not all terminals/logs displayed colors correctly. Adds the ability to suppress any color via `--suppress-colors` cli arg.
Thanks @drewski3420 for the contribution 🎉
=> [FEATURE] Add ability to suppress colors via CLI arg

docs/source/config_reference/scripting/scripting_functions.rst, src/ytdl_sub/script/functions/string_functions.py, tests/unit/script/functions/test_string_functions.py
Closes https://github.com/jmbannon/ytdl-sub/issues/1006
=> [FEATURE] Add `join` and `strip` string functions to scripting

docs/source/config_reference/scripting/scripting_functions.rst, src/ytdl_sub/script/functions/__init__.py, src/ytdl_sub/script/functions/print_functions.py, tests/unit/script/functions/test_print_functions.py
Add the ability to print custom messages in override scripts. Adds the functions
- `print`
- `print_if_true`
- `print_if_false`
Will be used to make under-the-hood preset things more verbose.
=> [FEATURE] Add scripting print functions

docs/source/config_reference/scripting/entry_variables.rst, src/ytdl_sub/entries/entry.py, src/ytdl_sub/entries/script/variable_definitions.py
Adds `height` and `width` entry variables.
=> [FEATURE] `height` and `width` variables

docs/source/config_reference/subscription_yaml.rst, docs/source/guides/getting_started/first_sub.rst, docs/source/guides/install/docker.rst, docs/source/index.rst, docs/source/introduction.rst
WIP: Includes changes so far [to review the built and hosted docs](https://discord.com/channels/994270357957648404/1102703969266049174/1405926351718060173).
I try to keep my commits clean and atomic with any more detailed discussion in the commit messages, so best to review this commit-by-commit.
Refs #1270
=> [DOCS] Clarifications for first time users

docs/source/config_reference/config_yaml.rst, docs/source/guides/getting_started/index.rst, docs/source/guides/install/docker.rst, docs/source/introduction.rst, docs/source/prebuilt_presets/helpers.rst, src/ytdl_sub/prebuilt_presets/helpers/throttle_protection.yaml, tests/integration/plugins/test_throttle_protection.py
The collection of changes I've been working on that are ready for review now. Mostly minor clarifications coming from recent discussions.
Review commit by commit, yada yada.
=> [DOCS] Various clarifications

docs/source/config_reference/plugins.rst, docs/source/faq/index.rst, src/ytdl_sub/plugins/date_range.py, src/ytdl_sub/validators/string_datetime.py
Stacked on #1292.
[Clarify re-download date TZ margins](https://discord.com/channels/994270357957648404/1102703969266049174/1408092149492224060)
=> [DOCS] faq: Clarify re-download date TZ margins

docker/Dockerfile, docker/Dockerfile.gui, docker/Dockerfile.ubuntu, docker/root/custom-cont-init.d/defaults, docker/testing/docker-compose.yml
Closes
- Deno requirement: https://github.com/jmbannon/ytdl-sub/issues/1340
- yt-dlp announcement: https://github.com/yt-dlp/yt-dlp/issues/14404
- Docker cron log double-logging: https://github.com/jmbannon/ytdl-sub/issues/1202 (thanks @timetocode for https://github.com/jmbannon/ytdl-sub/pull/1330 !)
- Missing pip dependency when updating yt-dlp: https://github.com/jmbannon/ytdl-sub/issues/1346
=> [DOCKER] Include Deno dependency, other fixes
